volumes:
  data:

services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    volumes:
      - data:/var/www/FreshRSS/data
      - /mnt/Config/freshrss/extensions:/var/www/FreshRSS/extensions
    ports:
      - "9876:9876"
    environment:
      TZ: America/New_York
      CRON_MIN: "3,33"
      LISTEN: 9876
      # TRUSTED_PROXY: 172.16.0.1/12 192.168.0.1/16
