version: '3.3'
services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "81:81" # Admin Web Port
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
      DISABLE_IPV6: "true"
    volumes:
      -  /usr/share/npm:/data
      - ./letsencrypt:/etc/letsencrypt

  goaccess:
    image: xavierh/goaccess-for-nginxproxymanager:latest
    container_name: goaccess
    restart: always
    ports:
        - "7880:7880"
    environment:
        - TZ=America/New_York
        - SKIP_ARCHIVED_LOGS=False #optional
        - DEBUG=False #optional
        - BASIC_AUTH=False #optional
        - EXCLUDE_IPS=127.0.0.1 #optional - comma delimited 
        - LOG_TYPE=NPM #optional - more information below
    volumes:
    - /usr/share/npm/logs:/opt/log
    #- /path/to/host/custom:/opt/custom #optional, required if using log_type = CUSTOM
