services:
  cobalt-api:
    image: ghcr.io/imputnet/cobalt:10
    init: true
    read_only: true
    restart: unless-stopped
    container_name: cobalt-api
    ports:
      - 9000:9000/tcp
    environment:
      API_URL: "https://cobalt-api.skibidi.cc/"
    labels:
      - com.centurylinklabs.watchtower.scope=cobalt

  cobalt-web:
    image: ghcr.io/imputnet/cobalt:10
    restart: unless-stopped
    container_name: cobalt-web
    init: true
    ports:
      - 8991:9001/tcp
    environment:
      WEB_URL: "https://cobalt.skibidi.cc/"
      API_URL: "https://cobalt-api.skibidi.cc/"
    labels:
      - com.centurylinklabs.watchtower.scope=cobalt

    # watchtower updates the cobalt image automatically
    watchtower:
      image: ghcr.io/containrrr/watchtower
      restart: unless-stopped
      command: --cleanup --scope cobalt --interval 900 --include-restarting
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
