version: "3"
services:

  sonarr:
    image: ghcr.io/linuxserver/sonarr:develop
    container_name: sonarr
    network_mode: "container:gluetun"
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /share/homes/chief/Config/Sonarr:/config
      - /share/Shows:/tv
      - /share/Incoming:/downloads
    ports:
      - 8989:8989
    restart: always

  radarr:
    image: ghcr.io/linuxserver/radarr:develop 
    network_mode: "container:gluetun"
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /share/homes/chief/Config/Radarr:/config
      - /share/Movies:/movies
      - /share/Incoming:/downloads
    ports:
      - 7878:7878
    restart: always

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    network_mode: "container:gluetun"
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /share/homes/chief/Config/Prowlarr:/config
    ports:
      - 9696:9696
    restart: always
