services:
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    network_mode: "container:gluetun"
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
      - WHITELIST=
    volumes:
      - /share/Config/transmission:/config
      - /share/Incoming:/downloads
      - /share/Movies:/movies
      - /share/Shows:/tv
    restart: always

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    network_mode: "container:gluetun"
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /share/Config/sabnzbd:/config
      - /share/Incoming:/downloads
      - /share/Movies:/movies
      - /share/Shows:/tv
    restart: always
