version: "2.1"
services:

  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
      - WHITELIST=
    volumes:
      - /share/homes/chief/Config/Transmission:/config
      - /share/Incoming:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /share/homes/chief/Config/Sabnzbd:/config
      - /share/Incoming:/downloads
      - /share/Incoming/tmp:/incomplete-downloads
    ports:
      - 9090:8080
    restart: unless-stopped

networks:
  default:
    external:
      name: arr_default