version: "3"
services:
  streamer:
    image: ghcr.io/chiefy/docker-ffmpeg-mp4-folder:latest
    container_name: streamer
    restart: unless-stopped
    environment:
      - VIDEO_DIR=/mnt/Movies/TDS
      - OWNCAST_STREAM_KEY=${OWNCAST_STREAM_KEY}
      - OWNCAST_STREAM_URL=${OWNCAST_STREAM_URL}
    volumes:
      - "/mnt/Movies:/mnt/Movies"

  owncast:
    image: owncast/owncast:latest
    container_name: owncast
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "1935:1935"
      - "8765:8080"
    volumes:
      - "/usr/share/owncast:/app/data"
