services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr:develop
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /config/sonarr:/config
      - /shows:/tv
      - /incoming:/downloads
    ports:
      - 8989:8989
    restart: always

  radarr:
    image: ghcr.io/linuxserver/radarr:develop
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /config/radarr:/config
      - /movies:/movies
      - /incoming:/downloads
    ports:
      - 7878:7878
    restart: always

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /config/prowlarr:/config
    ports:
      - 9696:9696
    restart: always
