version: "3.8"

services:
  linkding:
    container_name: linkding
    image: sissbruecker/linkding:latest
    environment:
      - PUID=0
      - PGID=33
      - TZ=America/New_York
    ports:
      - "9990:9090"
    volumes:
      - "/usr/share/linkding:/etc/linkding/data"
    restart: always
