services:
  comfyui:
    image: yanwk/comfyui-boot:cu121
    container_name: comfyui
    runtime: nvidia
    restart: unless-stopped
    environment:
      CLI_ARGS: ""
    volumes:
      - /run/media/chief/BigBoy/ollama/comfy:/home/runner
    ports:
      - 8188:8188
    networks:
      - lama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    volumes:
      - /run/media/chief/BigBoy/ollama/data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    ports:
      - "8000:8080"
    networks:
      - lama
  
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    runtime: nvidia
    volumes:
      - /run/media/chief/BigBoy/ollama:/root/.ollama
    ports:
      - "3000:11434"
    networks:
      - lama
    mem_limit: 20g
    mem_reservation: 10g
    cpus: 0.75
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
