services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    ports:
      - "5800:5800"
    environment:
      - MYJDOWNLOADER_EMAIL=${MYJDOWNLOADER_EMAIL}
      - MYJDOWNLOADER_PASSWORD=${MYJDOWNLOADER_PASSWORD}
      - MYJDOWNLOADER_DEVICE_NAME=blakey
      - JDOWNLOADER_HEADLESS=1
    volumes:
      - "/mnt/Config/jdownloader:/config:rw"
      - "/mnt/Incoming:/output:rw"
